/**
 * Validate Metrics Script
 * 
 * Reads the metrics-summary.json generated by compare-results.ts and validates
 * that TPR >= 90% and FPR < 10% for the bWAPP dataset.
 * 
 * Usage:
 *   npx tsx tests/debug/validate-metrics.ts
 * 
 * Exit codes:
 *   0 - All metrics pass thresholds
 *   1 - One or more metrics fail thresholds
 */

import fs from 'fs/promises';
import path from 'path';

interface MetricsSummary {
  truePositives: number;
  falseNegatives: number;
  falsePositives: number;
  totalManual: number;
  totalAutomated: number;
  truePositiveRate: number;
  falsePositiveRate: number;
  precision: number;
  recall: number;
  f1Score: number;
  details: {
    truePositivePages: string[];
    falseNegativePages: string[];
    falsePositivePages: string[];
  };
}

const TPR_THRESHOLD = 0.9;  // 90% minimum
const FPR_THRESHOLD = 0.1;  // 10% maximum

async function validateMetrics(): Promise<void> {
  const metricsPath = path.resolve(__dirname, 'metrics-summary.json');
  
  let metrics: MetricsSummary;
  try {
    const raw = await fs.readFile(metricsPath, 'utf-8');
    metrics = JSON.parse(raw) as MetricsSummary;
  } catch (err) {
    console.error('❌ Failed to read metrics-summary.json');
    console.error('   Run "npx tsx tests/debug/compare-results.ts" first to generate metrics.');
    process.exit(1);
  }

  console.log('📊 Validating Detection Metrics');
  console.log('================================');
  console.log();
  
  let allPassed = true;

  // Validate TPR
  const tprPercent = (metrics.truePositiveRate * 100).toFixed(1);
  const tprThresholdPercent = (TPR_THRESHOLD * 100).toFixed(0);
  if (metrics.truePositiveRate >= TPR_THRESHOLD) {
    console.log(`✅ True Positive Rate: ${tprPercent}% (threshold: ≥${tprThresholdPercent}%)`);
  } else {
    console.log(`❌ True Positive Rate: ${tprPercent}% (threshold: ≥${tprThresholdPercent}%)`);
    allPassed = false;
    if (metrics.details.falseNegativePages.length > 0) {
      console.log(`   Missing detections on: ${metrics.details.falseNegativePages.join(', ')}`);
    }
  }

  // Validate FPR
  const fprPercent = (metrics.falsePositiveRate * 100).toFixed(1);
  const fprThresholdPercent = (FPR_THRESHOLD * 100).toFixed(0);
  if (metrics.falsePositiveRate < FPR_THRESHOLD) {
    console.log(`✅ False Positive Rate: ${fprPercent}% (threshold: <${fprThresholdPercent}%)`);
  } else {
    console.log(`❌ False Positive Rate: ${fprPercent}% (threshold: <${fprThresholdPercent}%)`);
    allPassed = false;
    if (metrics.details.falsePositivePages.length > 0) {
      console.log(`   False positives on: ${metrics.details.falsePositivePages.join(', ')}`);
    }
  }

  console.log();
  console.log('Additional Metrics:');
  console.log(`   Precision: ${(metrics.precision * 100).toFixed(1)}%`);
  console.log(`   Recall: ${(metrics.recall * 100).toFixed(1)}%`);
  console.log(`   F1 Score: ${(metrics.f1Score * 100).toFixed(1)}%`);
  console.log();
  console.log(`   True Positives: ${metrics.truePositives}`);
  console.log(`   False Negatives: ${metrics.falseNegatives}`);
  console.log(`   False Positives: ${metrics.falsePositives}`);
  console.log();

  if (allPassed) {
    console.log('✅ All metric thresholds passed!');
    process.exit(0);
  } else {
    console.log('❌ One or more metric thresholds failed.');
    process.exit(1);
  }
}

validateMetrics().catch((err) => {
  console.error('Validation failed:', err);
  process.exit(1);
});
