# GitHub Actions CI/CD Integration Example
# This workflow runs security scans and uploads results to GitHub Security tab

name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scan
    - cron: '0 2 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    permissions:
      # Required for uploading SARIF results
      security-events: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install chromium
      
      - name: Run DAST Security Scan
        run: |
          npx dast-scan ${{ secrets.STAGING_URL }} \
            --formats sarif,json,html \
            --output ./security-reports \
            --parallel 2 \
            --headless
        continue-on-error: true
      
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security-reports/*.sarif
          category: dast-scan
      
      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: security-reports/
          retention-days: 30
      
      - name: Check for critical vulnerabilities
        run: |
          # Fail build if critical vulnerabilities found
          CRITICAL_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "critical")] | length' security-reports/*.json | head -1)
          
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Found $CRITICAL_COUNT critical vulnerability(ies)"
            exit 1
          else
            echo "✅ No critical vulnerabilities found"
          fi
      
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('security-reports/*.json', 'utf8'));
            
            const summary = `## 🔐 Security Scan Results
            
            - **Total vulnerabilities:** ${report.summary.total}
            - **Critical:** ${report.summary.critical}
            - **High:** ${report.summary.high}
            - **Medium:** ${report.summary.medium}
            - **Low:** ${report.summary.low}
            
            ${report.summary.critical > 0 ? '❌ **Action required:** Critical vulnerabilities found!' : '✅ **No critical issues**'}
            
            View full report in the artifacts section.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
